# Use a container-based environment
sudo: false

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - pypy3

matrix:
  include:
    - name: "lint"
      python: 3.7
      env:
        - TEST_CMD="pre-commit run --all-files"
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
    - name: "pypy3"
      python: pypy3

env:
  - MONGOENGINE=latest_pip
  - MONGOENGINE=dev
  - TEST_CMD="tox -e $(echo py$TRAVIS_PYTHON_VERSION-me_$MONGOENGINE | tr -d . | sed -e 's/pypypy/pypy/') -- --with-coverage"

services:
  - mongodb

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install coveralls
  - travis_retry pip install flake8
  - travis_retry pip install tox>=3.14
  - travis_retry pip install virtualenv
  - travis_retry pip install pre-commit

# Cache dependencies installed via pip
cache: pip

script:
  - $TEST_CMD

after_success:
  - coveralls --verbose

notifications:
  irc: irc.freenode.org#flask-mongoengine

# Only run builds on the master branch and GitHub releases (tagged as vX.Y.Z)
branches:
  only:
    - master
    - /^v.*$/

# Whenever a new release is created via GitHub, publish it on PyPI.
deploy:
  provider: pypi
  user: wojcikstefan
  password:
    secure: ZShEfSeu1pUHPGWtO5JAERp3nkG1omFIDxz/N+qNEJGwIRxXH6S0E17p9jaRAwrBY11F6ecajOgz1E1ICovYf8IitOP8I/CyieF6EPV7Bv4PZyKJdWGzT/Edjrt+wAjY7Kwlr2Gkh9Tu1lChZcWvhyMVPYCgqyA2yP0W2b9kC4Y=

  # create a source distribution and a pure python wheel for faster installs
  distributions: "sdist bdist_wheel"

  # only deploy on tagged commits (aka GitHub releases) and only for the
  # parent repo's builds running Python 2.7 along with dev MongoEngine (we run
  # Travis against many different Python and MongoEngine versions and we don't
  # want the deploy to occur multiple times).
  on:
    tags: true
    condition: "$MONGOENGINE = dev"
    python: 3.6
    repo: MongoEngine/flask-mongoengine
