language: python

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
- pypy3

env:
- MONGOENGINE=0.8
- MONGOENGINE=0.9
- MONGOENGINE=0.10.0
- MONGOENGINE=dev

before_install:
- travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- travis_retry sudo apt-get update
- travis_retry sudo apt-get autoremove
- travis_retry sudo apt-get autoclean
- travis_retry sudo apt-get install mongodb-org-server

install:
- travis_retry pip install --upgrade pip
- travis_retry pip install coveralls
- travis_retry pip install flake8
- travis_retry pip install tox>=1.9
- travis_retry pip install "virtualenv<14.0.0"  # virtualenv>=14.0.0 has dropped Python 3.2 support (and pypy3 is based on py32)
- travis_retry tox -e $(echo py$TRAVIS_PYTHON_VERSION-me$MONGOENGINE | tr -d . | sed -e 's/pypypy/pypy/') -- -e test

before_script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e flake8; fi

after_script:
- coveralls --verbose

script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION-me$MONGOENGINE | tr -d . | sed -e 's/pypypy/pypy/') -- --with-coverage

notifications:
  irc: irc.freenode.org#flask-mongoengine

branches:
  only:
  - master
  - dev

# Whenever a new release is created via GitHub, publish it on PyPI.
deploy:
  provider: pypi
  user: wojcikstefan
  password:
    secure: ZShEfSeu1pUHPGWtO5JAERp3nkG1omFIDxz/N+qNEJGwIRxXH6S0E17p9jaRAwrBY11F6ecajOgz1E1ICovYf8IitOP8I/CyieF6EPV7Bv4PZyKJdWGzT/Edjrt+wAjY7Kwlr2Gkh9Tu1lChZcWvhyMVPYCgqyA2yP0W2b9kC4Y=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: MongoEngine/flask-mongoengine
